# Generated by Django 5.0.7 on 2025-08-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_facilities',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('owner', 'Owner'), ('tenant', 'Tenant'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
